theme: jekyll-theme-leap-day
title: Privacy Policy | LiftStation.cloud
description: This is the privacy policy for the LiftStation.cloud software. LiftStation.cloud allows you to enter well and lift station data through an app, and generate Excel EPD Reports.
